name: Build Go binaries

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: get tag
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: Use tag
      run: echo ${{steps.tag.outputs.tag}}

    - run: mkdir bin
    - name: Build for RPi Zero W
      run: GOOS=linux GOARCH=arm GOARM=6 go build -o bin/pimon-zerow-${{ steps.tag.outputs.tag }}

    - name: Build for RPi 4 B
      run: GOOS=linux GOARCH=arm GOARM=7 go build -o bin/pimon-rpi4b-${{ steps.tag.outputs.tag }}

    - name: Copy dir to server
      uses: nogsantos/scp-deploy@master
      with:
        src: bin/*
        port: 22
        host: ${{ secrets.HOST }}
        remote: pimon
        user: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}

